apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: odoo-scw
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  storageClassName: microk8s-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data
  namespace: odoo-scw
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  storageClassName: microk8s-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-addons
  namespace: odoo-scw
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  storageClassName: microk8s-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
