apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-common
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tao-thewarat/k8s-infra.git'
    targetRevision: HEAD
    path: manifests/odoo/infra/common
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
