apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: bitbucket-pr-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: bitbucket-dep
      eventSourceName: bitbucket-pr
      eventName: bitbucket-pr

  triggers:
    - template:
        name: workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: pr-check-
                namespace: argo
              spec:
                entrypoint: debug
                arguments:
                  parameters:
                    - name: message
                      value: "default-repo"
                templates:
                  - name: debug
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
      parameters:
        - src:
            dependencyName: bitbucket-dep
            dataKey: body.message
          dest: spec.arguments.parameters.0.value
