apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: bitbucket-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
                namespace: argo
              spec:
                entrypoint: main
                arguments:
                  parameters:
                    - name: branch
                      value: default-branch
                    - name: repo
                      value: default-repo
                    - name: commit
                      value: default-commit

                volumeClaimTemplates:
                  - metadata:
                      name: work
                    spec:
                      accessModes: ["ReadWriteOnce"]
                      resources:
                        requests:
                          storage: 5Gi

                templates:
                  - name: main
                    steps:
                      # 2. Set status inprogress ของทั้ง pre-commit + unit-test พร้อมกัน
                      - - name: set-status-inprogress-pre-commit
                          template: set-status
                          arguments:
                            parameters:
                              - name: commit
                                value: "{{workflow.parameters.commit}}"
                              - name: state
                                value: "INPROGRESS"
                              - name: repo
                                value: "{{workflow.parameters.repo}}"
                              - name: branch
                                value: "{{workflow.parameters.branch}}"
                              - name: key
                                value: "pre-commit"
                              - name: description
                                value: "pre-commit"

                        - name: set-status-inprogress-unittest
                          template: set-status
                          arguments:
                            parameters:
                              - name: commit
                                value: "{{workflow.parameters.commit}}"
                              - name: state
                                value: "INPROGRESS"
                              - name: repo
                                value: "{{workflow.parameters.repo}}"
                              - name: branch
                                value: "{{workflow.parameters.branch}}"
                              - name: key
                                value: "unit-test"
                              - name: description
                                value: "unit-test"

                      # 1. Clone ก่อน (รันเดี่ยว)
                      - - name: git-clone
                          template: git-clone
                          arguments:
                            parameters:
                              - name: branch
                                value: "{{workflow.parameters.branch}}"
                              - name: repo
                                value: "{{workflow.parameters.repo}}"

                      # 3. หาไฟล์ที่เปลี่ยน (รันเดี่ยว)
                      - - name: changed-files
                          template: get-changed-files
                          arguments:
                            parameters:
                              - name: commit
                                value: "{{workflow.parameters.commit}}"
                              - name: repo
                                value: "{{workflow.parameters.repo}}"

                      # 4. รัน pre-commit (เดี่ยว)
                      - - name: pre-commit
                          template: pre-commit
                          arguments:
                            parameters:
                              - name: files
                                value: "/work/changed_files.txt"

                      # 5. update status ของ pre-commit
                      - - name: set-status-success
                          template: set-status
                          when: "{{steps.pre-commit.status}} == Succeeded"
                          arguments:
                            parameters:
                              - name: commit
                                value: "{{workflow.parameters.commit}}"
                              - name: state
                                value: "SUCCESSFUL"
                              - name: repo
                                value: "{{workflow.parameters.repo}}"
                              - name: branch
                                value: "{{workflow.parameters.branch}}"
                              - name: key
                                value: "pre-commit"
                              - name: description
                                value: "pre-commit"

                        - name: set-status-failed
                          template: set-status
                          when: "{{steps.pre-commit.status}} == Failed"
                          arguments:
                            parameters:
                              - name: commit
                                value: "{{workflow.parameters.commit}}"
                              - name: state
                                value: "FAILED"
                              - name: repo
                                value: "{{workflow.parameters.repo}}"
                              - name: branch
                                value: "{{workflow.parameters.branch}}"
                              - name: key
                                value: "pre-commit"
                              - name: description
                                value: "pre-commit"


                  # --- Clone repo ---
                  - name: git-clone
                    inputs:
                      parameters:
                        - name: branch
                        - name: repo
                    container:
                      image: alpine/git:latest
                      workingDir: /work
                      command: [sh, -c]
                      args:
                        - |
                          echo ">>> Setting up SSH"
                          mkdir -p ~/.ssh
                          cp /ssh/id_rsa ~/.ssh/id_rsa
                          cp /ssh/known_hosts ~/.ssh/known_hosts
                          chmod 600 ~/.ssh/id_rsa

                          echo ">>> Cloning repo"
                          git clone --depth 1 --branch {{inputs.parameters.branch}} \
                            --single-branch git@bitbucket.org:{{inputs.parameters.repo}}.git .
                      volumeMounts:
                        - name: work
                          mountPath: /work
                        - name: ssh-key
                          mountPath: /ssh
                          readOnly: true

                  # --- Get changed files ---
                  - name: get-changed-files
                    inputs:
                      parameters:
                        - name: commit
                        - name: repo
                    container:
                      image: alpine:3.18
                      workingDir: /work
                      command: [sh, -c]
                      args:
                        - |
                          echo ">>> Installing curl and jq"
                          apk add --no-cache curl jq

                          echo ">>> Calling Bitbucket API"
                          curl --request GET \
                            --url "https://api.bitbucket.org/2.0/repositories/{{inputs.parameters.repo}}/diffstat/{{inputs.parameters.commit}}" \
                            -u "${BITBUCKET_USERNAME}:${BITBUCKET_TOKEN}" \
                            --header "Accept: application/json" \
                          | jq -r '.values[].new?.path // .values[].old?.path' > /work/changed_files.txt

                          echo ">>> Files changed:"
                          cat /work/changed_files.txt
                      envFrom:
                        - secretRef:
                            name: bitbucket-credentials
                      volumeMounts:
                        - name: work
                          mountPath: /work

                  # --- Run pre-commit ---
                  - name: pre-commit
                    inputs:
                      parameters:
                        - name: files
                    script:
                      image: python:3.11-slim
                      workingDir: /work
                      command: [sh]
                      source: |
                        set -e
                        apt-get update && apt-get install -y git
                        pip install pre-commit
                        echo ">>> Running pre-commit"
                        cat changed_files.txt | xargs pre-commit run --files
                      volumeMounts:
                        - name: work
                          mountPath: /work

                  # --- Set commit status ---
                  - name: set-status
                    inputs:
                      parameters:
                        - name: commit
                        - name: state
                        - name: repo
                        - name: branch
                        - name: key
                        - name: description
                    container:
                      image: curlimages/curl:8.9.1
                      command: [sh, -c]
                      args:
                        - |
                          echo ">>> Setting commit status to {{inputs.parameters.state}}"
                          curl --request POST \
                            --url "https://api.bitbucket.org/2.0/repositories/{{inputs.parameters.repo}}/commit/{{inputs.parameters.commit}}/statuses/build" \
                            -u "${BITBUCKET_USERNAME}:${BITBUCKET_TOKEN}" \
                            --header "Content-Type: application/json" \
                            --data '{
                              "key": "{{inputs.parameters.key}}",
                              "state": "{{inputs.parameters.state}}",
                              "description": "{{inputs.parameters.description}}",
                              "url": "https://argo-workflows.imotif.io/workflows/argo/{{workflow.name}}?tab=workflow&uid={{workflow.uid}}",
                              "refname": "{{inputs.parameters.branch}}"
                            }'
                      envFrom:
                        - secretRef:
                            name: bitbucket-credentials

                volumes:
                  - name: ssh-key
                    secret:
                      secretName: git-ssh-key
          parameters:
            - src:
                dependencyName: bitbucket-dep
                dataKey: body.pullrequest.source.branch.name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: bitbucket-dep
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: bitbucket-dep
                dataKey: body.pullrequest.source.commit.hash
              dest: spec.arguments.parameters.2.value
